import type { LevelConfig, VeilId } from "./types"

export const LEVEL_CONFIGS: Record<VeilId, LevelConfig> = {
    0: {
        veilId: 0,
        lanes: 3,
        survivalSeconds: 20,
        baseSpeed: 280,
        maxSpeedMultiplier: 2.0,
        baseSpawnInterval: 0.9,
        minSpawnInterval: 0.35,
        obstacleTypes: ["single"],
        laneShift: false,
        reverseObstacles: false,
        taunts: false,
        glueWalls: false,
    },
    1: {
        veilId: 1,
        lanes: 4,
        survivalSeconds: 25,
        baseSpeed: 310,
        maxSpeedMultiplier: 2.3,
        baseSpawnInterval: 0.8,
        minSpawnInterval: 0.3,
        obstacleTypes: ["single", "double"],
        laneShift: false,
        reverseObstacles: false,
        taunts: false,
        glueWalls: false,
    },
    2: {
        veilId: 2,
        lanes: 4,
        survivalSeconds: 30,
        baseSpeed: 340,
        maxSpeedMultiplier: 2.5,
        baseSpawnInterval: 0.75,
        minSpawnInterval: 0.25,
        obstacleTypes: ["single", "double", "wall"],
        laneShift: true,
        reverseObstacles: false,
        taunts: false,
        glueWalls: false,
    },
    3: {
        veilId: 3,
        lanes: 5,
        survivalSeconds: 35,
        baseSpeed: 370,
        maxSpeedMultiplier: 2.8,
        baseSpawnInterval: 0.7,
        minSpawnInterval: 0.22,
        obstacleTypes: ["single", "double", "wall"],
        laneShift: true,
        reverseObstacles: true,
        taunts: false,
        glueWalls: false,
    },
    4: {
        veilId: 4,
        lanes: 5,
        survivalSeconds: 45,
        baseSpeed: 400,
        maxSpeedMultiplier: 3.0,
        baseSpawnInterval: 0.65,
        minSpawnInterval: 0.2,
        obstacleTypes: ["single", "double", "wall", "glue"],
        laneShift: true,
        reverseObstacles: true,
        taunts: true,
        glueWalls: true,
    },
}

/** Boss taunts that scroll across the screen during veil 4 */
export const BOSS_TAUNTS: string[] = [
    "veil.taunt.will_to_bind",
    "veil.taunt.adhesive_destiny",
    "veil.taunt.no_escape",
    "veil.taunt.principium",
    "veil.taunt.become_substrate",
    "veil.taunt.the_order_demands",
    "veil.taunt.nerve_language",
    "veil.taunt.yield_percentage",
]
