import type { CosmeticRarity, CosmeticType } from "./CosmeticManager"

export interface CosmeticDefinition {
    id: string
    type: CosmeticType
    name: string
    description: string
    unlockHint: string
    icon: string
    rarity: CosmeticRarity
    cssClass?: string
    trailConfig?: TrailConfig
}

export interface TrailConfig {
    colors: string[]
    shapes: string[]
    /** Size range [min, max] */
    size: [number, number]
}

export const COSMETIC_DEFINITIONS: CosmeticDefinition[] = [
    // ── Themes ─────────────────────────────────────────────────────────────

    {
        id: "win95",
        type: "theme",
        name: "Windows 95",
        description: "The classic baseline",
        unlockHint: "Always unlocked",
        icon: "🪟",
        rarity: "common",
    },
    {
        id: "mac-classic",
        type: "theme",
        name: "Mac Classic",
        description: "Clean and familiar",
        unlockHint: "Change the locale",
        icon: "🍎",
        rarity: "common",
    },
    {
        id: "apple2",
        type: "theme",
        name: "Apple II",
        description: "Monochrome green, retro",
        unlockHint: "Become a hacker",
        icon: "🍏",
        rarity: "common",
    },
    {
        id: "c64",
        type: "theme",
        name: "Commodore 64",
        description: "Purple and blue, blocky",
        unlockHint: "Write a program",
        icon: "💾",
        rarity: "common",
    },
    {
        id: "amiga",
        type: "theme",
        name: "Amiga Workbench",
        description:
            "Orange, blue, and white 4-color palette with beveled panels",
        unlockHint: "All aboard",
        icon: "🖼️",
        rarity: "uncommon",
    },
    {
        id: "next",
        type: "theme",
        name: "NeXTSTEP",
        description:
            "Dark grey, clean black titlebars, sophisticated minimalism",
        unlockHint: "Build the full stack",
        icon: "⬛",
        rarity: "uncommon",
    },
    {
        id: "vaporwave",
        type: "theme",
        name: "Vaporwave",
        description:
            "Pink, purple, and cyan with translucent panels and neon glow",
        unlockHint: "Find three ways",
        icon: "🌸",
        rarity: "rare",
    },
    {
        id: "golden",
        type: "theme",
        name: "Prestige Gold",
        description:
            "Black and gold with animated shimmer and serif typography",
        unlockHint: "Receive a windfall",
        icon: "👑",
        rarity: "rare",
    },
    {
        id: "nocturnal",
        type: "theme",
        name: "Nocturnal",
        description: "Deep crimson-black palette with warm blood-red accents",
        unlockHint: "Encounter the will of the world",
        icon: "🌑",
        rarity: "rare",
    },
    {
        id: "void",
        type: "theme",
        name: "The Void",
        description:
            "Deep purple-black with faint green accent and eerie spacing",
        unlockHint: "Behold yourself",
        icon: "🕳️",
        rarity: "legendary",
    },
    {
        id: "arcana",
        type: "theme",
        name: "Arcana",
        description:
            "Deep indigo and gold with ornate serif and mystical labels",
        unlockHint: "Complete all 22 Major Arcana",
        icon: "🔮",
        rarity: "legendary",
    },

    // ── Cursor Trails ─────────────────────────────────────────────────────

    {
        id: "default",
        type: "cursor-trail",
        name: "Sparkle",
        description: "The classic sparkle trail",
        unlockHint: "Always unlocked",
        icon: "✨",
        rarity: "common",
        trailConfig: {
            colors: ["#ffd700", "#ff6b35", "#ff1744", "#aa00ff"],
            shapes: ["✦", "✧", "⬥"],
            size: [6, 12],
        },
    },
    {
        id: "existentialist",
        type: "cursor-trail",
        name: "Existentialists",
        description: "Lightning and fire particles",
        unlockHint: "Complete the Existentialist faction collection",
        icon: "⚡",
        rarity: "rare",
        trailConfig: {
            colors: ["#ff4500", "#ff8c00", "#ffd700", "#8b0000"],
            shapes: ["⚡", "✦", "🔥"],
            size: [5, 10],
        },
    },
    {
        id: "idealist",
        type: "cursor-trail",
        name: "Idealists",
        description: "Star and form particles",
        unlockHint: "Complete the Idealist faction collection",
        icon: "🏛️",
        rarity: "rare",
        trailConfig: {
            colors: ["#4169e1", "#c0c0c0", "#ffd700", "#191970"],
            shapes: ["★", "☆", "⬡"],
            size: [6, 11],
        },
    },
    {
        id: "rationalist",
        type: "cursor-trail",
        name: "Rationalists",
        description: "Logic and infinity particles",
        unlockHint: "Complete the Rationalist faction collection",
        icon: "♾️",
        rarity: "rare",
        trailConfig: {
            colors: ["#b87333", "#cd7f32", "#daa520", "#8b7355"],
            shapes: ["∞", "⊛", "◎"],
            size: [7, 13],
        },
    },
    {
        id: "post-structuralist",
        type: "cursor-trail",
        name: "Post-Structuralists",
        description: "Spiral and fragment particles",
        unlockHint: "Complete the Post-Structuralist faction collection",
        icon: "🌀",
        rarity: "rare",
        trailConfig: {
            colors: ["#9370db", "#00ff7f", "#483d8b", "#2e8b57"],
            shapes: ["🌀", "~", "◆"],
            size: [6, 12],
        },
    },
    {
        id: "void-static",
        type: "cursor-trail",
        name: "Void Static",
        description: "Glitching particles from beyond the veil",
        unlockHint: "Endure suffering",
        icon: "📡",
        rarity: "legendary",
        trailConfig: {
            colors: ["#00ff80", "#ff4444", "#000000", "#ffffff"],
            shapes: ["█", "▓", "░"],
            size: [4, 10],
        },
    },
    {
        id: "earthen",
        type: "cursor-trail",
        name: "Earthen",
        description:
            "Earth-brown dust particles with occasional crescent shapes",
        unlockHint: "Navigate the unknown",
        icon: "🌿",
        rarity: "uncommon",
        trailConfig: {
            colors: ["#8b6914", "#a0522d", "#deb887", "#6b4226"],
            shapes: ["·", "⌒", "∘", "○"],
            size: [4, 9],
        },
    },
    {
        id: "arcade",
        type: "cursor-trail",
        name: "Arcade",
        description: "Retro pixel squares with scanline flicker",
        unlockHint: "Master the silver ball",
        icon: "🕹️",
        rarity: "uncommon",
        trailConfig: {
            colors: ["#ff0000", "#00ff00", "#ffff00", "#00ffff"],
            shapes: ["■", "▪", "□"],
            size: [4, 8],
        },
    },
    {
        id: "gold-rush",
        type: "cursor-trail",
        name: "Gold Rush",
        description: "Cascading coin sparkles with $ symbols",
        unlockHint: "Embrace irrational exuberance",
        icon: "💰",
        rarity: "rare",
        trailConfig: {
            colors: ["#ffd700", "#ffec8b", "#daa520", "#b8860b"],
            shapes: ["$", "✦", "●", "◉"],
            size: [5, 11],
        },
    },
    {
        id: "matrix",
        type: "cursor-trail",
        name: "Matrix",
        description: "Green falling characters that linger and fade",
        unlockHint: "Create something from nothing",
        icon: "🟩",
        rarity: "uncommon",
        trailConfig: {
            colors: ["#00ff41", "#008f11", "#003b00", "#00ff41"],
            shapes: ["0", "1", "ﾊ", "ﾐ", "ﾋ"],
            size: [5, 10],
        },
    },
    {
        id: "cosmic",
        type: "cursor-trail",
        name: "Cosmic",
        description:
            "Multi-layered stars, nebula puffs, and shooting star bursts",
        unlockHint: "Witness the full moon",
        icon: "🌌",
        rarity: "legendary",
        trailConfig: {
            colors: ["#e0e0ff", "#ff88cc", "#88ccff", "#ffcc44", "#aa44ff"],
            shapes: ["✦", "★", "·", "☆", "✶"],
            size: [3, 14],
        },
    },
    {
        id: "philosophia",
        type: "cursor-trail",
        name: "Philosophia",
        description:
            "Quill ink drops and floating Greek and German letter fragments",
        unlockHint: "Achieve the promethean",
        icon: "🪶",
        rarity: "legendary",
        trailConfig: {
            colors: ["#2b1810", "#4a3728", "#d4a574", "#ffd700"],
            shapes: ["φ", "ψ", "λ", "Σ", "ü", "ö"],
            size: [5, 12],
        },
    },
    {
        id: "instrumentalization",
        type: "cursor-trail",
        name: "Instrumentalization",
        description:
            "Sticky glue drip particles with collagen strands and horseshoe flashes",
        unlockHint: "Learn the plan",
        icon: "🐴",
        rarity: "legendary",
        trailConfig: {
            colors: ["#88aa22", "#6b8e23", "#9acd32", "#556b2f", "#8b4513"],
            shapes: ["◠", "≈", "∪", "⌒", "~"],
            size: [5, 13],
        },
    },
    {
        id: "typewriter",
        type: "cursor-trail",
        name: "Typewriter",
        description:
            "Ink splatter drops and floating typewriter key impressions",
        unlockHint: "Achieve redemption through exercises",
        icon: "⌨️",
        rarity: "legendary",
        trailConfig: {
            colors: ["#1a1a1a", "#333333", "#2b1810", "#4a3728"],
            shapes: ["·", ".", "○", "◯", "⊙"],
            size: [4, 10],
        },
    },

    // ── Desktop Wallpapers ────────────────────────────────────────────────

    {
        id: "default",
        type: "wallpaper",
        name: "Default",
        description: "The standard desktop background",
        unlockHint: "Always unlocked",
        icon: "🖥️",
        rarity: "common",
        cssClass: "",
    },
    {
        id: "existentialist-dusk",
        type: "wallpaper",
        name: "Existentialist Dusk",
        description: "Dusty amber-to-crimson gradient evoking the abyss",
        unlockHint: "Complete the Existentialist faction collection",
        icon: "⚡",
        rarity: "rare",
        cssClass: "wp-existentialist-dusk",
    },
    {
        id: "idealist-marble",
        type: "wallpaper",
        name: "Idealist Marble",
        description: "Cool steel blue, structured and clean",
        unlockHint: "Complete the Idealist faction collection",
        icon: "🏛️",
        rarity: "rare",
        cssClass: "wp-idealist-marble",
    },
    {
        id: "rationalist-blueprint",
        type: "wallpaper",
        name: "Rationalist Blueprint",
        description: "Dark navy with geometric grid overlay",
        unlockHint: "Complete the Rationalist faction collection",
        icon: "♾️",
        rarity: "rare",
        cssClass: "wp-rationalist-blueprint",
    },
    {
        id: "post-structural-void",
        type: "wallpaper",
        name: "Post-Structural Void",
        description: "Dark purple bleeding into green",
        unlockHint: "Complete the Post-Structuralist faction collection",
        icon: "🌀",
        rarity: "rare",
        cssClass: "wp-post-structural-void",
    },
    {
        id: "prestige-gold",
        type: "wallpaper",
        name: "Prestige Gold",
        description: "Gold gradient",
        unlockHint: "Prestige 3 or more times",
        icon: "🏆",
        rarity: "rare",
        cssClass: "wp-prestige-gold",
    },
    {
        id: "beyond-the-veil",
        type: "wallpaper",
        name: "Beyond the Veil",
        description: "Dark void with drifting geometric patterns",
        unlockHint: "Witness the twilight of the idols",
        icon: "🕳️",
        rarity: "legendary",
        cssClass: "wp-beyond-veil",
    },
    {
        id: "pasture",
        type: "wallpaper",
        name: "Pasture",
        description: "Gentle green gradient with faint grass texture",
        unlockHint: "Take the first step",
        icon: "🌾",
        rarity: "common",
        cssClass: "wp-pasture",
    },
    {
        id: "ocean",
        type: "wallpaper",
        name: "Ocean",
        description: "Calm horizontal blue gradient bands",
        unlockHint: "Find calm",
        icon: "🌊",
        rarity: "common",
        cssClass: "wp-ocean",
    },
    {
        id: "terminal-green",
        type: "wallpaper",
        name: "Terminal Green",
        description: "Green-on-black CRT with subtle scanline overlay",
        unlockHint: "Enter witness protection",
        icon: "🖥️",
        rarity: "uncommon",
        cssClass: "wp-terminal-green",
    },
    {
        id: "blueprint",
        type: "wallpaper",
        name: "Blueprint",
        description: "Technical grid with faint schematic line drawings",
        unlockHint: "Build an assembly line",
        icon: "📐",
        rarity: "uncommon",
        cssClass: "wp-blueprint",
    },
    {
        id: "stable",
        type: "wallpaper",
        name: "Stable",
        description: "Warm wood-grain planks with hay-colored highlights",
        unlockHint: "Enter the world of memory",
        icon: "🏚️",
        rarity: "rare",
        cssClass: "wp-stable",
    },
    {
        id: "starfield",
        type: "wallpaper",
        name: "Starfield",
        description: "Deep space with layered stars and slow twinkle animation",
        unlockHint: "Reach for the stars",
        icon: "⭐",
        rarity: "legendary",
        cssClass: "wp-starfield",
    },
    {
        id: "aurora",
        type: "wallpaper",
        name: "Aurora",
        description: "Animated northern lights with slow-moving color bands",
        unlockHint: "Reach the highest level",
        icon: "🌌",
        rarity: "legendary",
        cssClass: "wp-aurora",
    },
    {
        id: "trading-floor",
        type: "wallpaper",
        name: "Trading Floor",
        description:
            "Animated scrolling ticker lines with candlestick patterns",
        unlockHint: "Harvest an extraordinary amount",
        icon: "📈",
        rarity: "legendary",
        cssClass: "wp-trading-floor",
    },

    // ── Window Chrome ─────────────────────────────────────────────────────

    {
        id: "default",
        type: "window-chrome",
        name: "Default",
        description: "The standard window chrome",
        unlockHint: "Always unlocked",
        icon: "🪟",
        rarity: "common",
    },
    {
        id: "minimal",
        type: "window-chrome",
        name: "Minimal",
        description: "Nearly borderless with hairline dividers",
        unlockHint: "Keep a clean desk",
        icon: "➖",
        rarity: "common",
        cssClass: "chrome-minimal",
    },
    {
        id: "terminal",
        type: "window-chrome",
        name: "Terminal",
        description: "Green-on-black with blinking cursor in titlebar",
        unlockHint: "Read the manual",
        icon: "💻",
        rarity: "uncommon",
        cssClass: "chrome-terminal",
    },
    {
        id: "frontier",
        type: "window-chrome",
        name: "Frontier",
        description: "Wood and leather title bars",
        unlockHint: "Complete the full spiral",
        icon: "🤠",
        rarity: "rare",
        cssClass: "chrome-frontier",
    },
    {
        id: "corporate",
        type: "window-chrome",
        name: "Corporate",
        description: "Dark glass title bars",
        unlockHint: "Climb to level 20",
        icon: "🏢",
        rarity: "rare",
        cssClass: "chrome-corporate",
    },
    {
        id: "vintage",
        type: "window-chrome",
        name: "Vintage",
        description: "Sepia-toned chrome",
        unlockHint: "Earn 50 or more achievements",
        icon: "📜",
        rarity: "rare",
        cssClass: "chrome-vintage",
    },
    {
        id: "sanguine",
        type: "window-chrome",
        name: "Sanguine",
        description: "Deep burgundy titlebars with a hint of dripping",
        unlockHint: "Visit during the darkest hours",
        icon: "🩸",
        rarity: "rare",
        cssClass: "chrome-sanguine",
    },
    {
        id: "neon",
        type: "window-chrome",
        name: "Neon",
        description: "Glowing colored border that pulses with text-shadow glow",
        unlockHint: "Trigger a display glitch",
        icon: "💡",
        rarity: "rare",
        cssClass: "chrome-neon",
    },
    {
        id: "dial-up",
        type: "window-chrome",
        name: "Dial-Up",
        description: "Static and noise title bars",
        unlockHint: "Defeat what lurks beyond",
        icon: "📡",
        rarity: "legendary",
        cssClass: "chrome-dialup",
    },
    {
        id: "arcane",
        type: "window-chrome",
        name: "Arcane",
        description: "Ornate gold filigree borders with animated shimmer",
        unlockHint: "Reach the highest academic rank",
        icon: "✨",
        rarity: "legendary",
        cssClass: "chrome-arcane",
    },

    // ── System Fonts ──────────────────────────────────────────────────────

    {
        id: "default",
        type: "system-font",
        name: "System",
        description: "Default sans-serif",
        unlockHint: "Always unlocked",
        icon: "Aa",
        rarity: "common",
    },
    {
        id: "monospace",
        type: "system-font",
        name: "Monospace",
        description: "Courier-style monospace",
        unlockHint: "Become a hacker",
        icon: "🔤",
        rarity: "common",
        cssClass: "font-monospace",
    },
    {
        id: "serif",
        type: "system-font",
        name: "Serif",
        description: "Classic Georgia serif",
        unlockHint: "Become an author",
        icon: "📖",
        rarity: "common",
        cssClass: "font-serif",
    },
    {
        id: "handwritten",
        type: "system-font",
        name: "Handwritten",
        description: "Cursive script font",
        unlockHint: "Leave your signature",
        icon: "✍️",
        rarity: "uncommon",
        cssClass: "font-handwritten",
    },
    {
        id: "terminal",
        type: "system-font",
        name: "Terminal",
        description: "Monospace with green tint on all text",
        unlockHint: "Become self-aware",
        icon: "💻",
        rarity: "uncommon",
        cssClass: "font-terminal",
    },
    {
        id: "pixel",
        type: "system-font",
        name: "Pixel",
        description: "Retro bitmap pixel font",
        unlockHint: "Collect a bounty",
        icon: "👾",
        rarity: "rare",
        cssClass: "font-pixel",
    },
    {
        id: "blackletter",
        type: "system-font",
        name: "Blackletter",
        description: "Fraktur gothic typeface",
        unlockHint: "Study German Idealism",
        icon: "🖋️",
        rarity: "legendary",
        cssClass: "font-blackletter",
    },

    // ── Taskbar Styles ────────────────────────────────────────────────────

    {
        id: "default",
        type: "taskbar-style",
        name: "Default",
        description: "The standard taskbar",
        unlockHint: "Always unlocked",
        icon: "▬",
        rarity: "common",
    },
    {
        id: "minimal",
        type: "taskbar-style",
        name: "Minimal",
        description: "Thin bar, reduced padding, semi-transparent",
        unlockHint: "Keep a clean desk",
        icon: "━",
        rarity: "common",
        cssClass: "taskbar-minimal",
    },
    {
        id: "chunky",
        type: "taskbar-style",
        name: "Chunky",
        description:
            "Extra thick with exaggerated 3D bevels and oversized buttons",
        unlockHint: "Visit the factory floor",
        icon: "▰",
        rarity: "uncommon",
        cssClass: "taskbar-chunky",
    },
    {
        id: "dark-glass",
        type: "taskbar-style",
        name: "Dark Glass",
        description: "Dark translucent with blur backdrop",
        unlockHint: "Embrace the dark side",
        icon: "🌑",
        rarity: "uncommon",
        cssClass: "taskbar-dark-glass",
    },
    {
        id: "holographic",
        type: "taskbar-style",
        name: "Holographic",
        description:
            "Animated rainbow gradient border with color-shifting sheen",
        unlockHint: "Complete everything",
        icon: "🌈",
        rarity: "legendary",
        cssClass: "taskbar-holographic",
    },

    // ── Window Animations ─────────────────────────────────────────────────

    {
        id: "default",
        type: "window-animation",
        name: "Default",
        description: "The standard open and close animation",
        unlockHint: "Always unlocked",
        icon: "▶️",
        rarity: "common",
    },
    {
        id: "none",
        type: "window-animation",
        name: "None",
        description: "Instant open and close, no animation",
        unlockHint: "Find calm",
        icon: "⏹️",
        rarity: "common",
        cssClass: "anim-none",
    },
    {
        id: "fade",
        type: "window-animation",
        name: "Fade",
        description: "Smooth opacity fade in and out",
        unlockHint: "Explore the desktop",
        icon: "🔅",
        rarity: "common",
        cssClass: "anim-fade",
    },
    {
        id: "bounce",
        type: "window-animation",
        name: "Bounce",
        description: "Spring overshoot bounce on open",
        unlockHint: "Enjoy popups",
        icon: "🔵",
        rarity: "uncommon",
        cssClass: "anim-bounce",
    },
    {
        id: "viscous",
        type: "window-animation",
        name: "Viscous",
        description:
            "Noticeably slow, thick-feeling ease like pulling through something dense",
        unlockHint: "Reach phase 3",
        icon: "🫠",
        rarity: "uncommon",
        cssClass: "anim-viscous",
    },
    {
        id: "cascade",
        type: "window-animation",
        name: "Cascade",
        description: "Staggered cascade with slight rotation",
        unlockHint: "Decorate the interior",
        icon: "🃏",
        rarity: "rare",
        cssClass: "anim-cascade",
    },
    {
        id: "glitch",
        type: "window-animation",
        name: "Glitch",
        description:
            "Brief glitch tear effect with random jitters before settling",
        unlockHint: "Trigger a blue screen",
        icon: "⚡",
        rarity: "legendary",
        cssClass: "anim-glitch",
    },

    // ── Startup Sounds ────────────────────────────────────────────────────

    {
        id: "none",
        type: "startup-sound",
        name: "Silent",
        description: "No startup sound",
        unlockHint: "Always unlocked",
        icon: "🔇",
        rarity: "common",
    },
    {
        id: "chime",
        type: "startup-sound",
        name: "Chime",
        description: "A short pleasant chime",
        unlockHint: "Reach phase 2",
        icon: "🔔",
        rarity: "common",
    },
    {
        id: "retro",
        type: "startup-sound",
        name: "Retro",
        description: "8-bit jingle",
        unlockHint: "All aboard",
        icon: "🎮",
        rarity: "uncommon",
    },
    {
        id: "modem",
        type: "startup-sound",
        name: "Modem",
        description: "Dial-up handshake sequence",
        unlockHint: "Establish a dial-up connection",
        icon: "📞",
        rarity: "rare",
    },
    {
        id: "whinny",
        type: "startup-sound",
        name: "Whinny",
        description: "A horse whinny on boot",
        unlockHint: "Whisper to the horse",
        icon: "🐎",
        rarity: "rare",
    },
    {
        id: "orchestral",
        type: "startup-sound",
        name: "Orchestral",
        description: "Grand orchestral swell",
        unlockHint: "Consult the oracle",
        icon: "🎻",
        rarity: "legendary",
    },
]

export function getCosmeticsForType(type: CosmeticType): CosmeticDefinition[] {
    return COSMETIC_DEFINITIONS.filter((d) => d.type === type)
}

export function getCosmeticDef(
    type: CosmeticType,
    id: string
): CosmeticDefinition | undefined {
    return COSMETIC_DEFINITIONS.find((d) => d.type === type && d.id === id)
}
