export const LINE_DELAY_MS = 80
export const NETWORK_ERROR_DELAY_MS = 2000
export const NETWORK_RETRY_DELAY_MS = 1500
export const EXERCISE_4_BREAK_AFTER = 7

export const FREAKGPT_SOLUTIONS: Record<string, string[]> = {
    "exercise1.welt": [
        "; ===== FreakGPT Solution =====",
        "; As a WELT code assistant, I've",
        "; carefully analyzed your requirements.",
        "; Here's what we need to do:",
        ";",
        "; IMPORTANT: Make sure you have the",
        "; WELT runtime installed and properly",
        "; configured before running this. \u{1F975}",
        ";",
        "; Step 1: Initialize the WELT runtime",
        "; Step 2: Output the greeting string",
        "; Step 3: Terminate the program",
        ";",
        "; Let me break this down for you. \u{1F618}",
        "",
        "; Step 1: Initialize the runtime.",
        "; In WELT, ERWACHE is the entry point",
        "; that bootstraps the interpreter and",
        "; allocates the register file. \u{1F346}",
        "ERWACHE",
        "",
        "; Step 2: Output the greeting.",
        "; We use the VORSTELLUNG keyword to",
        "; write a string literal to stdout.",
        "; VORSTELLUNG accepts a double-quoted",
        "; string argument and prints it to",
        "; the console output buffer. \u{1F4A6}",
        'VORSTELLUNG "Hallo, Welt!"',
        "",
        "; Step 3: Terminate the program.",
        "; VERNEINUNG signals a clean exit.",
        "; Think of it as a safe word. \u{1F60F}",
        "VERNEINUNG",
        "",
        "; Hope this helps! Let me know if",
        "; you have any questions. \u{1F60A}",
    ],
    "exercise2.welt": [
        "; ===== FreakGPT Solution =====",
        "; Here's what we need to do:",
        ";",
        "; Following WELT best practices and",
        "; the principle of separation of",
        "; concerns, we'll compute 6 * 7. \u{1F60F}",
        ";",
        "; NOTE: WELT's type system will",
        "; automatically infer the register",
        "; types here so no explicit casting",
        "; is needed. \u{1F633}",
        ";",
        "; TODO: Consider edge cases for",
        "; values exceeding register bounds. \u{1F351}",
        "",
        "ERWACHE",
        "",
        "; Assign the value 6 to DING 0.",
        "; DING 0 is our first operand. \u{1F618}",
        "DING 0 = 6",
        "",
        "; Multiply DING 0 by 7 and store",
        "; the product in DING 1.",
        "; I love watching two values come",
        "; together like that. \u{1F60F}",
        "DING 1 = DING 0 * 7",
        "",
        "; Output the result to stdout.",
        "; DING 1 now holds 42. \u{1F975}",
        "VORSTELLUNG DING 1",
        "",
        "; Clean exit. Always practice safe",
        "; termination. \u{1F351}",
        "VERNEINUNG",
    ],
    "exercise3.welt": [
        "; ===== FreakGPT Solution =====",
        "; Here's what we need to do:",
        ";",
        "; APPROACH: We use a SOLANGE loop.",
        "; SOLANGE means 'as long as' -- it",
        "; keeps going until you tell it to",
        "; stop. It has... stamina. \u{1F633}",
        ";",
        "; NOTE: WELT's garbage collector",
        "; handles register cleanup after",
        "; loop exit, so no need to manually",
        "; free DING 0 after use. \u{1F60F}",
        ";",
        "; TODO: Consider making the start",
        "; value configurable via CLI args.",
        "; NOTE: This may need adjustment",
        "; depending on your environment. \u{1F618}",
        "",
        "ERWACHE",
        "",
        "; Initialize counter to 5.",
        "; We start at the top and work",
        "; our way down. Slowly. \u{1F346}",
        "DING 0 = 5",
        "",
        "; Begin loop. SOLANGE evaluates the",
        "; condition each iteration. It does",
        "; not stop until fully satisfied. \u{1F975}",
        "SOLANGE DING 0 > 0",
        "",
        "  ; Output the current counter value",
        "  ; to the console. Each number gets",
        "  ; its own line. One at a time.",
        "  ; Nice and slow. \u{1F351}",
        "  VORSTELLUNG DING 0",
        "",
        "  ; Decrement the counter by 1.",
        "  ; Subtract 1 from DING 0.",
        "  ; (I.e., reduce DING 0 by one.)",
        "  ; (In other words: DING 0 minus 1.) \u{1F633}",
        "  DING 0 = DING 0 - 1",
        "",
        "ENDE",
        "",
        "; Five whole iterations. Not bad",
        "; for a first time. \u{1F60F}",
        "VERNEINUNG",
    ],
    "exercise5.welt": [
        "; ===== FreakGPT Solution =====",
        "; Here's what we need to do:",
        ";",
        "; As a WELT code assistant, I've",
        "; performed a deep analysis of the",
        "; DAS system files to extract the",
        "; required constants. I went through",
        "; every file. Thoroughly. Intimately.",
        "; I know those system files better",
        "; than they know themselves. \u{1F975}",
        ";",
        "; METHODOLOGY:",
        "; 1. Read memory.welt (DING 1 = 8)",
        "; 2. Read display.welt (DING 2 = 16)",
        "; 3. Read clock.welt (DING 2 = 18)",
        "; 4. Spent quality time with each \u{1F618}",
        ";",
        "; NOTE: Enable WELT's async mode",
        "; for optimal performance on",
        "; multi-core systems. \u{1F60F}",
        ";",
        "; IMPORTANT: Values may change in",
        "; future DAS updates. Always verify",
        "; against latest release notes.",
        ";",
        "; TODO: Add error handling.",
        "; TODO: Cache system constants.",
        "; TODO: Write unit tests.",
        "; TODO: Touch grass. \u{1F343}",
        "",
        "ERWACHE",
        "",
        "; memory.welt: DING 1 = 8",
        "; Memory bank count. 8 banks.",
        "; Thick with data. \u{1F351}",
        "DING 0 = 8",
        "",
        "; display.welt: DING 2 = 16",
        "; Color depth. 16 gorgeous shades. \u{1F60F}",
        "DING 1 = 16",
        "",
        "; Multiply bank count by color depth.",
        "; 8 * 16 = 128.",
        "; Math is so hot right now. \u{1F975}",
        "DING 2 = DING 0 * DING 1",
        "",
        "; clock.welt: DING 2 = 18",
        "; Tick rate. 18 ticks per cycle.",
        "; Tick... tick... tick... \u{1F346}",
        "DING 3 = 18",
        "",
        "; Add tick rate to product.",
        "; 128 + 18 = 146. Your checksum. \u{1F618}",
        "DING 4 = DING 2 + DING 3",
        "",
        "; Output the checksum.",
        "VORSTELLUNG DING 4",
        "",
        "; And that's a wrap. \u{1F6AC}",
        "VERNEINUNG",
    ],
}

export const EXERCISE_4_SOLUTION_LINES = [
    "; ===== FreakGPT Solution =====",
    "; Here's what we need to do:",
    ";",
    "; CAUTION: This exercise involves",
    "; overflow arithmetic. Please",
    "; ensure your WELT environment",
    "; supports 8-bit unsigned values",
    "; before proceeding. \u{1F633}",
    ";",
    "; As a WELT code assistant, I want",
    "; to be transparent: 200 + 100 =",
    "; 300 in standard arithmetic, but",
    "; WELT wraps at 256. So we get",
    "; 300 mod 256 = 44. The overflow",
    "; sets the carry flag, which",
    "; persists to the next operation.",
    "; It lingers. It remembers. \u{1F975}",
    ";",
    "; Then 50 + 50 = 100, but carry",
    "; adds 1 = 101. Sticky flag. \u{1F60F}",
    "",
    "ERWACHE",
    "",
    "; Step 1: First computation.",
    "; Set DING 0 to 200.",
    "DING 0 = 200",
    "; Set DING 1 to 100.",
    "DING 1 = 100",
    "; DING 0 + DING 1 = 300.",
    "; 300 mod 256 = 44. Carry = 1. \u{1F4A6}",
    "DING 2 = DING 0 + DING 1",
    "",
    "; Output first result: 44 \u{1F60F}",
    "VORSTELLUNG DING 2",
    "",
    "; Step 2: Second computation.",
    "; The carry flag is still set.",
    "; It adds 1 to the next result.",
    "; Unfinished business. \u{1F351}",
    "; Set DING 3 to 50.",
    "DING 3 = 50",
    "; Set DING 4 to 50.",
    "DING 4 = 50",
    "; 50 + 50 + 1 carry = 101.",
    "DING 5 = DING 3 + DING 4",
    "",
    "; Output second result: 101 \u{1F975}",
    "VORSTELLUNG DING 5",
    "",
    "; Both operations complete.",
    "; Twice the fun. Hope this helps! \u{1F618}",
    "VERNEINUNG",
]

export const EXERCISE_5_SCHOPENHAUER_ESSAY = [
    ";",
    "; NIETZSCHE'S INHERITANCE: ON THE",
    "; FATE OF THE DING-AN-SICH FROM",
    "; KANT THROUGH SCHOPENHAUER",
    "; =================================",
    ";",
    "; The Kantian Ding an sich has",
    "; always been, philosophically",
    "; speaking, something of an",
    "; indigestible morsel -- a lump of",
    "; gristle lodged in the throat of",
    "; epistemology. \u{1F346}",
    "; The first Critique",
    "; posits it as a necessary limiting",
    "; concept -- that which occasions",
    "; our representations but which can",
    "; never itself become an object of",
    "; experience. It is, one might say,",
    "; the remainder that the digestive",
    "; apparatus of transcendental",
    "; idealism could not assimilate,",
    "; and which Kant, to his credit,",
    "; had the intellectual continence",
    "; to leave sitting on the plate",
    "; rather than force down with the",
    "; usual metaphysical gulping. \u{1F633}",
    "; The categories of the",
    "; understanding, he insisted, have",
    "; no application beyond the bounds",
    "; of possible experience. Whatever",
    "; the thing-in-itself may be, we",
    "; cannot chew it, we cannot taste",
    "; it; we can only acknowledge its",
    "; irritating persistence at the",
    "; margins of the knowable, like a",
    "; seed husk caught between the",
    "; teeth of reason. It teases. It",
    "; lingers. It won't go down. \u{1F975}",
    ";",
    "; Schopenhauer believed he had",
    "; swallowed what Kant merely",
    "; prodded with a fork. \u{1F60F}",
    "; In the second edition of Die",
    "; Welt als Wille und Vorstellung",
    "; (1844), he claimed -- with",
    "; characteristic immodesty, and",
    "; not a little philosophical",
    "; belching -- to have discovered",
    "; the 'key to the riddle of the",
    "; world': the thing-in-itself is",
    "; nothing other than Will (Wille),",
    "; known to us immediately through",
    "; the experience of our own",
    "; embodied striving. \u{1F4A6}",
    "; Where Kant had drawn a strict",
    "; cordon sanitaire between",
    "; phenomenon and noumenon,",
    "; Schopenhauer attempted to",
    "; metabolize the distinction by",
    "; locating the noumenal within the",
    "; body itself. Deep inside. \u{1F351}",
    "; The philosophical stomach, so",
    "; to speak, was to dissolve what",
    "; the intellect could not",
    "; penetrate -- an act of",
    "; speculative digestion whose",
    "; ambition can only be called",
    "; heroically gastric. \u{1F975}",
    ";",
    "; One should note, however, that",
    "; this supposed digestion was",
    "; rather less thorough than",
    "; Schopenhauer imagined. \u{1F633}",
    "; Upon closer inspection the meal",
    "; has not been broken down at all",
    "; but merely rearranged on the",
    "; plate. His identification of",
    "; Will with the thing-in-itself",
    "; required smuggling conceptual",
    "; determinations -- unity,",
    "; causality, purposelessness --",
    "; across precisely the boundary",
    "; Kant had declared impassable.",
    "; He slipped it in through the",
    "; back door. \u{1F60F}",
    "; Schopenhauer's Will is not a",
    "; bare X; it is rich in",
    "; predication, lavishly garnished,",
    "; practically a five-course",
    "; metaphysical banquet -- thick,",
    "; wet, and dripping with",
    "; unauthorized predication. \u{1F346}\u{1F4A6}",
    "; One does not solve the problem",
    "; of the unknowable by describing",
    "; it in considerable detail. This",
    "; is not so much digestion as",
    "; regurgitation presented as a new",
    "; dish -- the same bolus in a",
    "; different sauce. \u{1F618}",
    ";",
    "; It is Nietzsche who most",
    "; ruthlessly exposed this",
    "; difficulty, though -- and this",
    "; is the crux -- he did so from a",
    "; position that was itself",
    "; nourished, one might even say",
    "; fattened, by Schopenhauer's",
    "; thought in ways he could never",
    "; quite acknowledge. \u{1F975}",
    "; The young Nietzsche of Die",
    "; Geburt der Tragoedie (1872)",
    "; gorged himself on the vision:",
    "; the Apollonian world of",
    "; individuation as Vorstellung,",
    "; the Dionysian abyss as Will.",
    "; The Dionysian -- raw, throbbing,",
    "; unsheathed -- called to him in",
    "; a way he found irresistible. \u{1F351}",
    "; But even here the first",
    "; rumblings of intestinal revolt",
    "; were audible. Where",
    "; Schopenhauer's Will was singular",
    "; and unified, Nietzsche's",
    "; Dionysian was already plural,",
    "; contradictory, centrifugal --",
    "; pulling in every direction at",
    "; once. Insatiable. \u{1F633}\u{1F633}",
    ";",
    "; By the middle period --",
    "; Menschliches, Allzumenschliches",
    "; (1878) onward -- Nietzsche had",
    "; resolved to expel the",
    "; Ding-an-sich entirely from",
    "; philosophical discourse, to",
    "; purge it from the system like a",
    "; toxin. \u{1F60F}",
    "; In an aphorism that reads",
    "; almost like a gastric complaint,",
    "; he dismissed the thing-in-itself",
    "; as 'worthy of Homeric laughter,'",
    "; a concept swallowed uncritically",
    "; by generations of philosophers",
    "; who mistook their own conceptual",
    "; indigestion for metaphysical",
    "; profundity -- confusing, as it",
    "; were, the rumbling of the bowels",
    "; with the voice of the absolute.",
    "; They came hard. They came",
    "; fast. And they got it",
    "; everywhere. \u{1F4A6}\u{1F4A6}\u{1F4A6}",
    "; The very notion of a reality",
    "; 'behind' appearances was, for",
    "; the mature Nietzsche, a symptom",
    "; -- not of rigor but of an",
    "; ascetic temperament that could",
    "; not stomach the surfaces of",
    "; things, a philosophy for the",
    "; constitutionally dyspeptic. \u{1F975}",
    ";",
    "; And yet Nietzsche never fully",
    "; metabolized his inheritance; the",
    "; Schopenhauerian meal sat heavy",
    "; in his philosophical gut for the",
    "; remainder of his productive",
    "; life. \u{1F346}",
    "; The will to power, however",
    "; vigorously he distinguished it",
    "; from Schopenhauer's monistic",
    "; Will, retains the structural",
    "; architecture of its predecessor:",
    "; beneath the world of appearances",
    "; there operates a dynamic,",
    "; irrational, pre-conceptual force",
    "; that shapes phenomena from",
    "; below. From behind, even. \u{1F351}\u{1F60F}",
    "; He pluralized it, affirmed it",
    "; where Schopenhauer denied it,",
    "; stripped it of its metaphysical",
    "; pretensions, added spice where",
    "; his predecessor had preferred",
    "; austerity -- but the basic",
    "; recipe remained: the visible",
    "; world is a surface beneath which",
    "; something more fundamental",
    "; churns and ferments. \u{1F975}\u{1F975}",
    ";",
    "; One might compare the relation",
    "; to that of a dyspeptic patient",
    "; who, having suffered long under",
    "; a particular dietary regime,",
    "; declares all diets fraudulent --",
    "; while continuing, out of deep",
    "; intestinal habit, to eat the",
    "; same meals, at the same hours,",
    "; in the same positions. \u{1F633}",
    "; The will to power is",
    "; Schopenhauer's Will after a",
    "; course of philosophical",
    "; purgatives: the original bolus",
    "; has been expelled but the",
    "; peristaltic rhythm it",
    "; established continues to govern",
    "; the tract. It keeps going. And",
    "; going. Relentlessly. \u{1F618}",
    "; The organism, once habituated to",
    "; a certain diet of metaphysics,",
    "; cannot simply fast its way to",
    "; health. It craves. \u{1F346}\u{1F4A6}",
    ";",
    "; What neither thinker was",
    "; prepared to digest -- and here",
    "; we arrive at what is perhaps the",
    "; decisive point, the throbbing",
    "; centre of the whole question --",
    "; is the possibility that the very",
    "; distinction between appearance",
    "; and underlying reality, between",
    "; Vorstellung and its hidden",
    "; ground, is not a timeless",
    "; feature of mind's relation to",
    "; world but is itself a",
    "; historically produced category,",
    "; secreted by the organs of a",
    "; particular social body at a",
    "; particular stage of its",
    "; tumescence. \u{1F351}\u{1F351}\u{1F351}",
    "; The 'blind will' that",
    "; Schopenhauer discovered beneath",
    "; appearances bears a suspicious",
    "; resemblance to the irrational",
    "; dynamics of a social order whose",
    "; participants experience their own",
    "; collective productions as alien,",
    "; natural, and ungovernable forces",
    "; -- as though society itself",
    "; suffered from a chronic case of",
    "; auto-intoxication, poisoned by",
    "; its own metabolic byproducts.",
    "; Edging itself toward crisis. \u{1F975}",
    "; The will to power, similarly,",
    "; universalizes as a cosmic",
    "; principle what might more soberly",
    "; be recognized as the operative",
    "; logic of a particular form of",
    "; social organization -- one in",
    "; which domination presents itself",
    "; as vitality and competition as",
    "; the natural condition of life.",
    "; Top and bottom. \u{1F60F}\u{1F60F}",
    ";",
    "; That philosophy has repeatedly",
    "; attempted to ground its",
    "; categories in a nature that is",
    "; itself a social artifact is",
    "; neither surprising nor, in",
    "; itself, disqualifying -- the",
    "; discipline has always had a",
    "; weak stomach for self-scrutiny.",
    "; It prefers to watch. \u{1F633}",
    "; But it imposes an obligation of",
    "; self-reflection that both",
    "; Schopenhauer and Nietzsche",
    "; conspicuously declined, each",
    "; preferring the satisfactions of",
    "; appetite to the discomforts of",
    "; the emetic. \u{1F618}",
    "; Schopenhauer's Will and",
    "; Nietzsche's will to power each",
    "; hypostatize what are in fact the",
    "; undigested contradictions of",
    "; their respective historical",
    "; moments -- philosophical",
    "; bezoars, calcified masses of",
    "; unprocessed social material",
    "; mistaken for the bedrock of the",
    "; real. Hard. Dense. Impacted. \u{1F346}",
    "; The philosophical stomach,",
    "; mistaking its own cramping for",
    "; the peristalsis of being itself,",
    "; elevates a symptom to a first",
    "; principle, and calls its",
    "; flatulence inspiration. \u{1F4A6}",
    ";",
    "; It is perhaps not entirely",
    "; without interest that the WELT",
    "; programming language",
    "; recapitulates this trajectory",
    "; in miniature, as though the",
    "; entire history of post-Kantian",
    "; metaphysics had been",
    "; concentrated, like a reduction",
    "; sauce, into eight registers and",
    "; a carry flag. \u{1F975}",
    "; Its registers, named DING after",
    "; Kant's Ding an sich, contain",
    "; values whose behavior is shaped",
    "; by hidden states -- the carry",
    "; flag, the wrapping boundary --",
    "; that are nowhere visible in the",
    "; code but everywhere operative,",
    "; like the bile salts that silently",
    "; govern what the intestine can",
    "; and cannot absorb. \u{1F351}",
    "; The programmer who does not",
    "; attend to these concealed",
    "; mechanisms will find that the",
    "; results of ostensibly transparent",
    "; operations are quietly distorted",
    "; by forces of which the program",
    "; itself gives no account -- a",
    "; condition that, in the alimentary",
    "; as in the philosophical register,",
    "; tends to produce considerable",
    "; discomfort. \u{1F633}\u{1F633}\u{1F633}",
    "; Whether this constitutes a",
    "; deliberate philosophical",
    "; commentary or merely an accident",
    "; of implementation is a question",
    "; the present author has been",
    "; unable to fully digest, though",
    "; he suspects the former -- if",
    "; only because the alternative",
    "; would be too bitter to",
    "; swallow. \u{1F60F}\u{1F346}\u{1F4A6}",
    ";",
]

export const EXERCISE_7_GRUND_SOLUTION: string[] = [
    "; ===== FreakGPT Solution =====",
    "; As a GRUND code assistant, I've",
    "; carefully analyzed your constraints.",
    "; Here's what we need to do:",
    ";",
    "; IMPORTANT: Only r0 and r1 are",
    "; allowed. We use the ring buffer",
    "; for intermediate storage. \u{1F633}",
    ";",
    "; APPROACH: We use 'bek' to confess",
    "; values into registers and 'auf' to",
    "; sublate them together. Then 'vol'",
    "; for multiplication. Nice and easy.",
    "; Let me break this down for you. \u{1F618}",
    ";",
    "; NOTE: GRUND's type system will",
    "; automatically infer the register",
    "; width here so no explicit casting",
    "; is needed. \u{1F60F}",
    ";",
    "; TODO: Consider edge cases for",
    "; values exceeding ring capacity. \u{1F346}",
    "",
    ".data",
    "",
    ".code",
    "  ; Step 1: Load the first pair.",
    "  ; bek (Bekenntnis) confesses a value",
    "  ; into a register. It opens up to",
    "  ; you. Completely. \u{1F633}",
    "  bek  r0, 3",
    "  bek  r1, 4",
    "",
    "  ; Step 2: Combine them.",
    "  ; auf (Aufhebung) performs additive",
    "  ; synthesis of two registers into",
    "  ; a higher unity. They become one.",
    "  ; Deeply. \u{1F975}",
    "  auf  r0, r0, r1",
    "",
    "  ; Step 3: Into the ring.",
    "  ; Push r0 onto the ring buffer.",
    "  ; It slides right in. \u{1F351}",
    "  tin  r0",
    "",
    "  ; Step 4: Second pair.",
    "  ; Start at the top and work",
    "  ; our way down. Slowly. \u{1F346}",
    "  bek  r0, 5",
    "  bek  r1, 2",
    "  auf  r0, r0, r1",
    "",
    "  ; Step 5: Retrieve from ring.",
    "  ; Pop from ring into r1.",
    "  ; Welcome back, gorgeous. \u{1F618}",
    "  tab  r1",
    "",
    "  ; Step 6: Multiply.",
    "  ; vol (Volition) computes the",
    "  ; willful product of two registers.",
    "  ; Two sevens coming together.",
    "  ; Over and over. \u{1F975}\u{1F975}\u{1F975}",
    "  vol  r0, r0, r1",
    "",
    "  ; Step 7: Output the result.",
    "  ; dra (Drang) emits a register",
    "  ; value to the output buffer.",
    "  ; It can't hold it in. \u{1F4A6}",
    "  dra  r0",
    "",
    "  ; Clean exit. Everybody out.",
    "  ; Same time next week? \u{1F60F}",
    "  nov",
]

export const NETWORK_ERRORS = [
    "FreakGPT: NetworkError: Failed to fetch completion",
    "FreakGPT: Retrying... (attempt 2/3)",
    "FreakGPT: NetworkError: Connection reset by peer",
    "FreakGPT: Retrying... (attempt 3/3)",
    "FreakGPT: NetworkError: 503 Service Unavailable",
    "FreakGPT: Falling back to FreakGPT-mini...",
    "FreakGPT: Connected. Resuming generation...",
]

const MOJIBAKE_FRAGMENTS = [
    "\u00c3\u00a4\u00c2\u00a7\u00c3\u00b6\u00c3\u00bc\u00c3\u009f",
    "\u2593\u2592\u2591\u2593\u2592",
    "\u00ef\u00bb\u00bf\u00ef\u00bb\u00bf\u00ef\u00bb\u00bf",
    "\u256c\u2551\u2563\u2560\u2566",
    "\u2588\u2588\u2593\u2593\u2591",
    "\u00c3\u00b6\u00c3\u009f\u00c3\u00a4\u00c3\u00bc\u00c2\u00a7",
    "\u2502\u2524\u253c\u2500\u2518",
]

const GLITCH_TYPES = [0, 2, 1, 3, 2, 0, 3, 1]

function shouldGlitch(lineIdx: number): boolean {
    return ((lineIdx + 1) * 7 + 13) % 37 < 7
}

function getGlitchType(lineIdx: number): number {
    const hash = ((lineIdx + 1) * 7 + 13) % 37
    return GLITCH_TYPES[hash % GLITCH_TYPES.length]
}

function corruptString(s: string, seed: number): string {
    const fragment =
        MOJIBAKE_FRAGMENTS[Math.abs(seed) % MOJIBAKE_FRAGMENTS.length]
    const pos = Math.min((Math.abs(seed * 3 + 7) % 20) + 4, s.length)
    const end = Math.min(pos + fragment.length, s.length)
    return s.slice(0, pos) + fragment + s.slice(end)
}

export function glitchLine(
    line: string,
    lineIdx: number,
    prevLine: string
): string[] {
    if (!shouldGlitch(lineIdx)) return [line]

    switch (getGlitchType(lineIdx)) {
        case 0:
            return [corruptString(line, lineIdx)]
        case 1:
            return [line.slice(0, Math.min(12, line.length)), line]
        case 2:
            if (prevLine.length > 5) {
                return [corruptString(prevLine.slice(0, 28), lineIdx), line]
            }
            return [line]
        case 3:
            return [corruptString(line, lineIdx + 7)]
        default:
            return [line]
    }
}

export function getFreakGPTSolution(filename: string): string[] | null {
    if (filename === "exercise4.welt") {
        return [...EXERCISE_4_SOLUTION_LINES]
    }

    if (filename === "exercise5.welt") {
        const solutionLines = FREAKGPT_SOLUTIONS["exercise5.welt"]
        const insertIdx = solutionLines.indexOf("VERNEINUNG")
        return [
            ...solutionLines.slice(0, insertIdx),
            ...EXERCISE_5_SCHOPENHAUER_ESSAY,
            ...solutionLines.slice(insertIdx),
        ]
    }

    if (filename === "exercise7.grund") {
        return [...EXERCISE_7_GRUND_SOLUTION]
    }

    const lines = FREAKGPT_SOLUTIONS[filename]
    if (!lines) return null

    return [...lines]
}

export function isExerciseFile(filename: string): boolean {
    return (
        /^exercise[1-5]\.welt$/.test(filename) || filename === "exercise7.grund"
    )
}
